apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: renovate-github
configMapGenerator:
  - name: renovate-config
    files:
      - config.json
resources:
  - ../../base
  - secret.yaml

generatorOptions:
  disableNameSuffixHash: true
