apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
  - secret.yaml

configMapGenerator:
  - name: renovate-config
    files:
      - config.json

generatorOptions:
  disableNameSuffixHash: true