apiVersion: batch/v1
kind: CronJob
metadata:
  name: renovate-github
spec:
  schedule: "15 07 * * 2"
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: renovate-github
              image: renovate/renovate:latest
              volumeMounts:
                - name: config
                  mountPath: /opt/renovate/config.json
                  subPath: config.json
                - name: work
                  mountPath: '/tmp/renovate/'
              env:
                - name: LOG_LEVEL
                  value: info
              envFrom:
                - secretRef:
                    name: renovate-secret
          restartPolicy: Never
          volumes:
            - name: config
              configMap:
                name: renovate-config
            - name: work
              emptyDir: {}
